batch_size: 128
dataset_path: data/var_rename
device: cuda
dim_model: 128
dropout_attn: 0.0
dropout_emb: 0.1
dropout_mlp: 0.1
eval_every_n_samples: 1000000
grad_norm_max: 1.0
learning_rate: 0.0001
load_model_path: null
log_every_n_seconds: 3
log_fp: 4
lr_start_factor: 0.001
num_chains: 4
num_epochs: 1000
num_heads: 2
num_layers: 5
num_renames: 150
overwrite_existing_checkpoints: true
rope_base: 2000.0
run_name: sweep_7
save_every_n_seconds: 100
save_model_path: null
tensorboard_logdir: logs/var_rename
test_size: 10000
train_size: 1000000
warmup_steps: 4000
weight_decay: 0.01
